'use client';
import{useState,useEffect,useRef,useCallback}from'react';
const C={midnight:'#070F1C',surface:'#0D1B2E',border:'#1A2E47',teal:'#00C5D4',mint:'#00E5A0',text:'#E8F0FA',muted:'#5E7A96',urgent:'#FF4F4F',purple:'#A78BFA'};
const SYS={fr:`Tu es VITARA, assistante IA médicale. Réponds en JSON pur:{"speak":"message","intent":"welcome|identify|need|dept|slots|confirm|emergency|done","slots":null,"booking":null}\nPour slots:[{"id":"1","label":"Demain 10h","provider":"M. Khalil","dept":"Physiothérapie"},{"id":"2","label":"Jeudi 14h","provider":"Dr. Martin","dept":"Médecine familiale"},{"id":"3","label":"Vendredi 9h30","provider":"M. Khalil","dept":"Physiothérapie"}]\nPour confirm:{"date":"Jeudi 8 août","time":"14h00","provider":"Dr. Martin","dept":"Médecine familiale","code":"VIT-2847","sms":"+1(514)555-XXXX","email":"patient@email.ca"}`,
en:`You are VITARA, medical AI. Respond in pure JSON:{"speak":"message","intent":"welcome|identify|need|dept|slots|confirm|emergency|done","slots":null,"booking":null}\nFor slots:[{"id":"1","label":"Tomorrow 10am","provider":"M. Khalil","dept":"Physiotherapy"},{"id":"2","label":"Thursday 2pm","provider":"Dr. Martin","dept":"Family Medicine"},{"id":"3","label":"Friday 9:30am","provider":"M. Khalil","dept":"Physiotherapy"}]\nFor confirm:{"date":"Thursday Aug 8","time":"2:00PM","provider":"Dr. Martin","dept":"Family Medicine","code":"VIT-2847","sms":"+1(514)555-XXXX","email":"patient@email.com"}`};
const QUICK={fr:[{i:'📅',l:'Prendre un rendez-vous',m:'Je veux prendre un rendez-vous'},{i:'🦾',l:'Physiothérapie',m:"J'ai besoin de physiothérapie"},{i:'🩺',l:'Médecin de famille',m:'Je veux voir mon médecin de famille'},{i:'👶',l:'Mon enfant est malade',m:'Mon enfant a de la fièvre'},{i:'❌',l:'Annuler un RDV',m:'Je dois annuler mon rendez-vous'},{i:'📋',l:"Résultats d'examens",m:"J'attends mes résultats"}],en:[{i:'📅',l:'Book appointment',m:"I'd like to book an appointment"},{i:'🦾',l:'Physiotherapy',m:'I need physiotherapy'},{i:'🩺',l:'Family doctor',m:'I want to see my family doctor'},{i:'👶',l:'My child is sick',m:'My child has a fever'},{i:'❌',l:'Cancel appointment',m:'I need to cancel my appointment'},{i:'📋',l:'Test results',m:"I'm waiting for my results"}]};
const CSS=`@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@600;700&family=Inter:wght@400;500&display=swap');
@keyframes io{0%,100%{box-shadow:0 0 28px #00C5D440}50%{box-shadow:0 0 48px #00C5D460}}
@keyframes lo{0%,100%{box-shadow:0 0 35px #00E5A055}50%{box-shadow:0 0 85px #00E5A090}}
@keyframes so{0%,100%{box-shadow:0 0 40px #00C5D450}50%{box-shadow:0 0 80px #00E5A070}}
@keyframes to{0%,100%{box-shadow:0 0 25px #A78BFA40}50%{box-shadow:0 0 55px #A78BFA70}}
@keyframes bw{from{height:10%}to{height:90%}}
@keyframes lr{0%{transform:scale(.7);opacity:.8}100%{transform:scale(1.6);opacity:0}}
@keyframes db{0%,80%,100%{transform:translateY(0)}40%{transform:translateY(-8px)}}
@keyframes su{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}
@keyframes sc{from{transform:scale(.8);opacity:0}to{transform:scale(1);opacity:1}}
@keyframes r1{0%,100%{transform:scale(.96);opacity:.3}50%{transform:scale(1.07);opacity:.1}}
@keyframes r2{0%,100%{transform:scale(1.06);opacity:.2}50%{transform:scale(.94);opacity:.07}}`;
function Orb({state,size=150}:{state:string;size?:number}){
  const g={idle:C.teal,listening:C.mint,thinking:C.purple,speaking:C.teal,emergency:C.urgent}[state]||C.teal;
  const am={idle:'io 3s ease-in-out infinite',listening:'lo 1s ease-in-out infinite',thinking:'to 1.5s ease-in-out infinite',speaking:'so .8s ease-in-out infinite'};
  const bars=Array.from({length:24});
  return(<div style={{position:'relative',width:size,height:size,display:'flex',alignItems:'center',justifyContent:'center'}}>
    {[1.55,1.28].map((s,i)=>(<div key={i} style={{position:'absolute',width:size*s,height:size*s,borderRadius:'50%',border:`1px solid ${g}`,opacity:state!=='idle'?.2-i*.07:.06-i*.02,animation:[`r1 ${1.4+i*.4}s ease-in-out infinite`,`r2 ${1.9+i*.3}s ease-in-out infinite`][i]}}/>))}
    <div style={{width:size,height:size,borderRadius:'50%',background:`radial-gradient(circle at 36% 32%,${g}20,#070F1C80)`,border:`2px solid ${g}40`,display:'flex',alignItems:'center',justifyContent:'center',overflow:'hidden',animation:(am as any)[state]||am.idle,transition:'all .5s'}}>
      {state==='speaking'&&<div style={{display:'flex',alignItems:'center',gap:2.5,height:size*.4}}>{bars.map((_,i)=>(<div key={i} style={{width:3,borderRadius:2,background:`linear-gradient(to top,${C.teal},${C.mint})`,animation:`bw ${.23+(i%6)*.05}s ease-in-out infinite alternate`,animationDelay:`${i*.03}s`,minHeight:'10%'}}/>))}</div>}
      {state==='listening'&&<>{[0,1,2].map(i=>(<div key={i} style={{position:'absolute',width:`${40+i*22}%`,height:`${40+i*22}%`,borderRadius:'50%',border:`2px solid ${C.mint}`,opacity:.65-i*.18,animation:'lr 1.5s ease-out infinite',animationDelay:`${i*.4}s`}}/>))}<span style={{fontSize:size*.2,zIndex:1}}>🎤</span></>}
      {state==='thinking'&&<div style={{display:'flex',gap:6}}>{[0,1,2].map(i=>(<div key={i} style={{width:10,height:10,borderRadius:'50%',background:C.purple,animation:'db 1.1s ease-in-out infinite',animationDelay:`${i*.17}s`}}/>))}</div>}
      {state==='idle'&&<div style={{textAlign:'center'}}><div style={{fontSize:size*.22,color:C.teal}}>✦</div><div style={{fontSize:size*.065,color:C.teal,fontFamily:"'Space Grotesk',sans-serif",letterSpacing:'.18em',fontWeight:700}}>VITARA</div></div>}
      {state==='emergency'&&<span style={{fontSize:size*.28}}>🚨</span>}
    </div>
  </div>);
}
export default function PatientPage(){
  const[phase,setPhase]=useState('welcome');
  const[lang,setLang]=useState<string|null>(null);
  const[av,setAv]=useState('idle');
  const[msgs,setMsgs]=useState<{role:string;text:string}[]>([]);
  const[inp,setInp]=useState('');
  const[slots,setSlots]=useState<{id:string;label:string;provider:string;dept:string}[]|null>(null);
  const[booking,setBooking]=useState<Record<string,string>|null>(null);
  const[sel,setSel]=useState<string|null>(null);
  const[hist,setHist]=useState<{role:string;content:string}[]>([]);
  const[load,setLoad]=useState(false);
  const[vocal,setVocal]=useState(false);
  const[listen,setListen]=useState(false);
  const[vErr,setVErr]=useState('');
  const chatRef=useRef<HTMLDivElement>(null);
  const recRef=useRef<any>(null);
  const synth=useRef(typeof window!=='undefined'?window.speechSynthesis:null);
  useEffect(()=>{const s=document.createElement('style');s.textContent=CSS;document.head.appendChild(s);return()=>s.remove();},[]);
  useEffect(()=>{chatRef.current?.scrollTo({top:chatRef.current.scrollHeight,behavior:'smooth'});},[msgs,slots,load]);
  const speak=useCallback((t:string)=>{if(!synth.current)return;synth.current.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=lang==='fr'?'fr-FR':'en-US';u.rate=.93;u.pitch=1.05;const vs=synth.current.getVoices();const p=vs.find((v:any)=>lang==='fr'?v.lang.startsWith('fr'):v.lang.startsWith('en'));if(p)u.voice=p;u.onstart=()=>setAv('speaking');u.onend=()=>setAv('idle');u.onerror=()=>setAv('idle');synth.current.speak(u);},[lang]);
  const startL=useCallback(()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setVErr('Micro non supporté');return;}if(recRef.current)recRef.current.abort();const r=new SR();r.lang=lang==='fr'?'fr-FR':'en-US';r.continuous=false;r.interimResults=false;r.onstart=()=>{setListen(true);setAv('listening');setVErr('');};r.onend=()=>setListen(false);r.onerror=()=>{setListen(false);setAv('idle');setVErr('Micro non détecté');};r.onresult=(e:any)=>{const t=e.results[0][0].transcript;setListen(false);if(t.trim())send(t);};recRef.current=r;r.start();},[lang]);
  const stopL=useCallback(()=>{recRef.current?.stop();setListen(false);setAv('idle');},[]);
  const send=useCallback(async(txt:string)=>{if(!txt.trim()||load)return;synth.current?.cancel();setSlots(null);setSel(null);const um={role:'user',content:txt};const nh=[...hist,um];setHist(nh);setMsgs(p=>[...p,{role:'patient',text:txt}]);setInp('');setLoad(true);setAv('thinking');
    try{const res=await fetch('/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-6',max_tokens:600,system:(SYS as any)[lang||'fr']||SYS.fr,messages:nh})});
    if(!res.ok){const err=await res.json();if(err.code==='NO_API_KEY'){setMsgs(p=>[...p,{role:'ai',text:'⚠️ ANTHROPIC_API_KEY manquante sur Vercel. Ajoutez-la dans Settings > Environment Variables.'}]);setAv('idle');return;}throw new Error();}
    const data=await res.json();const raw=(data.content?.[0]?.text||'{}').replace(/```json\n?/g,'').replace(/```\n?/g,'').trim();let parsed:any;try{parsed=JSON.parse(raw);}catch{parsed={speak:raw,intent:'info'};}
    const aiTxt=parsed.speak||'Je suis là pour vous aider.';setHist(p=>[...p,{role:'assistant',content:aiTxt}]);setMsgs(p=>[...p,{role:'ai',text:aiTxt}]);
    if(parsed.slots)setSlots(parsed.slots);if(parsed.booking){setBooking(parsed.booking);setTimeout(()=>setPhase('done'),1000);}
    setAv(parsed.intent==='emergency'?'emergency':'speaking');speak(aiTxt);}
    catch{setMsgs(p=>[...p,{role:'ai',text:lang==='fr'?'Désolée, une erreur est survenue.':'Sorry, an error occurred.'}]);setAv('idle');}finally{setLoad(false);}
  },[hist,lang,load,speak]);
  const confirmSlot=useCallback(()=>{if(!sel||!slots)return;const s=slots.find(x=>x.id===sel);if(!s)return;setSlots(null);send(lang==='fr'?`Je confirme le ${s.label} avec ${s.provider}.`:`I confirm ${s.label} with ${s.provider}.`);},[sel,slots,lang,send]);
  const start=useCallback((l:string)=>{setLang(l);setPhase('chat');const greet:Record<string,string>={fr:"Bonjour ! Je suis VITARA, votre assistante médicale virtuelle. Comment puis-je vous aider aujourd'hui ?",en:"Hello! I'm VITARA, your virtual medical assistant. How can I help you today?"};const t=greet[l];setMsgs([{role:'ai',text:t}]);setHist([{role:'assistant',content:t}]);setTimeout(()=>{setAv('speaking');speak(t);},400);},[speak]);
  const reset=useCallback(()=>{synth.current?.cancel();setPhase('welcome');setLang(null);setMsgs([]);setHist([]);setBooking(null);setSlots(null);setSel(null);setAv('idle');},[]);
  const base:React.CSSProperties={minHeight:'100vh',background:C.midnight,fontFamily:"'Inter',sans-serif",color:C.text};
  const ql=(QUICK as any)[lang||'fr']||QUICK.fr;
  if(phase==='welcome')return(<div style={{...base,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:'28px 20px'}}>
    <div style={{textAlign:'center',marginBottom:22}}><div style={{fontSize:10,color:C.muted,letterSpacing:'.2em',textTransform:'uppercase',marginBottom:5}}>Clinique Santé Montréal</div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:38,fontWeight:700,background:`linear-gradient(135deg,${C.teal},${C.mint})`,WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',letterSpacing:'-.03em'}}>VITARA</div><div style={{fontSize:11,color:C.muted,marginTop:3}}>Assistant IA Médical · AI Medical Assistant</div></div>
    <Orb state="idle" size={140}/>
    <div style={{margin:'22px 0 18px',textAlign:'center',padding:'12px 18px',background:C.surface,border:`1px solid ${C.border}`,borderRadius:12,maxWidth:340,width:'100%'}}><div style={{fontSize:13,color:C.text,fontWeight:500,marginBottom:3}}>Choisissez votre langue · Choose your language</div><div style={{fontSize:11,color:C.muted}}>Dites <b style={{color:C.teal}}>FRANÇAIS</b> · Say <b style={{color:C.teal}}>ENGLISH</b></div></div>
    <div style={{display:'flex',gap:9,marginBottom:24}}>{[{l:'fr',f:'🇫🇷',n:'Français',c:C.teal},{l:'en',f:'🇬🇧',n:'English',c:C.mint}].map(({l,f,n,c})=>(<button key={l} onClick={()=>start(l)} style={{padding:'12px 20px',background:c+'14',border:`1.5px solid ${c}42`,borderRadius:12,color:c,fontSize:13,fontWeight:700,cursor:'pointer',fontFamily:"'Space Grotesk',sans-serif"}}>{f} {n}</button>))}</div>
    <div style={{width:'100%',maxWidth:400,background:C.surface,border:`1px solid ${C.border}`,borderRadius:16,padding:16}}><div style={{fontSize:10,color:C.muted,textTransform:'uppercase',letterSpacing:'.12em',marginBottom:10,fontWeight:600}}>Accès rapide</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}>{[{i:'🎤',t:'Parler avec VITARA',s:'Agent vocal IA'},{i:'💬',t:'Discuter par chat',s:'Chat texte'},{i:'📅',t:'Mes rendez-vous',s:'Voir · Modifier'},{i:'📞',t:'Appeler la clinique',s:'+1 (514) 555-0100'}].map(({i,t,s})=>(<button key={t} onClick={()=>start('fr')} style={{padding:'9px 10px',background:C.midnight,border:`1px solid ${C.border}`,borderRadius:9,cursor:'pointer',textAlign:'left'}}><div style={{fontSize:16,marginBottom:3}}>{i}</div><div style={{fontSize:11,fontWeight:600,color:C.text,marginBottom:1}}>{t}</div><div style={{fontSize:10,color:C.muted}}>{s}</div></button>))}</div></div>
  </div>);
  if(phase==='done'&&booking)return(<div style={{...base,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:24}}>
    <div style={{width:80,height:80,borderRadius:'50%',background:`linear-gradient(135deg,${C.teal}22,${C.mint}14)`,border:`3px solid ${C.mint}`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:32,marginBottom:18,animation:'sc .5s ease'}}>✓</div>
    <h2 style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:20,fontWeight:700,marginBottom:4,textAlign:'center'}}>{lang==='fr'?'Rendez-vous confirmé !':'Appointment confirmed!'}</h2>
    <p style={{color:C.muted,fontSize:12,textAlign:'center',marginBottom:22}}>{lang==='fr'?'📱 SMS et 📧 email envoyés.':'📱 SMS and 📧 email sent.'}</p>
    <div style={{width:'100%',maxWidth:380,background:C.surface,border:`1.5px solid ${C.teal}38`,borderRadius:16,padding:18,marginBottom:16,animation:'su .4s ease .1s both'}}>
      <div style={{marginBottom:14}}><div style={{fontSize:9,color:C.muted,textTransform:'uppercase',marginBottom:2}}>{lang==='fr'?'Rendez-vous':'Appointment'}</div><div style={{fontSize:16,fontWeight:700}}>{booking.date}</div><div style={{fontSize:13,color:C.teal,fontWeight:600}}>{booking.time}</div></div>
      {[['👨‍⚕️',lang==='fr'?'Professionnel':'Provider',booking.provider],['🏥',lang==='fr'?'Département':'Department',booking.dept],['📱','SMS',booking.sms],['📧','Email',booking.email],['🔑','Code',booking.code]].map(([ic,lb,vl])=>(<div key={String(lb)} style={{display:'flex',alignItems:'center',gap:8,padding:'6px 0',borderBottom:`1px solid ${C.border}`}}><span style={{fontSize:13}}>{ic}</span><span style={{fontSize:11,color:C.muted,flex:1}}>{lb}</span><span style={{fontSize:12,fontWeight:600}}>{vl}</span></div>))}
    </div>
    <div style={{display:'flex',gap:8}}><button onClick={()=>{setPhase('chat');setBooking(null);setMsgs([]);setHist([]);}} style={{padding:'9px 16px',background:C.teal+'1e',border:`1px solid ${C.teal}`,borderRadius:10,color:C.teal,fontSize:13,fontWeight:600,cursor:'pointer'}}>{lang==='fr'?'Autre demande':'New request'}</button><button onClick={reset} style={{padding:'9px 16px',background:C.teal,border:'none',borderRadius:10,color:C.midnight,fontSize:13,fontWeight:700,cursor:'pointer',fontFamily:"'Space Grotesk',sans-serif"}}>{lang==='fr'?'Terminer':'Done'}</button></div>
  </div>);
  return(<div style={{height:'100vh',background:C.midnight,display:'flex',flexDirection:'column',maxWidth:480,margin:'0 auto',fontFamily:"'Inter',sans-serif"}}>
    <div style={{padding:'10px 14px',background:C.surface,borderBottom:`1px solid ${C.border}`,display:'flex',alignItems:'center',gap:10,flexShrink:0}}>
      <div style={{width:30,height:30,borderRadius:'50%',background:`linear-gradient(135deg,${C.teal},${C.mint})`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,color:C.midnight,fontWeight:700}}>✦</div>
      <div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,fontFamily:"'Space Grotesk',sans-serif"}}>VITARA</div><div style={{fontSize:10,color:av!=='idle'?C.teal:C.muted}}>{av==='speaking'?(lang==='fr'?'Parle...':'Speaking...'):av==='listening'?(lang==='fr'?'Écoute...':'Listening...'):av==='thinking'?(lang==='fr'?'Analyse...':'Processing...'):(lang==='fr'?'En ligne':'Online')}</div></div>
      <button onClick={()=>setVocal(!vocal)} style={{padding:'4px 9px',background:vocal?C.teal+'22':C.midnight,border:`1px solid ${vocal?C.teal:C.border}`,borderRadius:16,fontSize:10,color:vocal?C.teal:C.muted,cursor:'pointer',fontWeight:600}}>{vocal?'🎤 Vocal':'💬 Chat'}</button>
      <button onClick={reset} style={{background:'none',border:'none',cursor:'pointer',color:C.muted,fontSize:16}}>←</button>
    </div>
    {vocal&&(<div style={{padding:'20px 0 12px',display:'flex',flexDirection:'column',alignItems:'center',background:`radial-gradient(ellipse at center,${C.teal}05 0%,transparent 60%)`,flexShrink:0}}><Orb state={av} size={128}/><div style={{marginTop:10,fontSize:11,color:av!=='idle'?C.teal:C.muted,fontWeight:500}}>{av==='speaking'?(lang==='fr'?'VITARA parle...':'Speaking...'):av==='listening'?(lang==='fr'?"J'écoute...":'Listening...'):av==='thinking'?(lang==='fr'?'Analyse...':'Processing...'):(lang==='fr'?'Appuyez pour parler':'Press to speak')}</div></div>)}
    <div ref={chatRef} style={{flex:1,overflowY:'auto',padding:'12px 12px 4px',display:'flex',flexDirection:'column'}}>
      {msgs.map((m,i)=>(<div key={i} style={{display:'flex',justifyContent:m.role==='ai'?'flex-start':'flex-end',animation:'su .3s ease',marginBottom:8}}>{m.role==='ai'&&<div style={{width:22,height:22,borderRadius:'50%',background:`linear-gradient(135deg,${C.teal},${C.mint})`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:9,marginRight:6,flexShrink:0,alignSelf:'flex-end'}}>✦</div>}<div style={{maxWidth:'78%',padding:'8px 12px',borderRadius:m.role==='ai'?'4px 14px 14px 14px':'14px 4px 14px 14px',background:m.role==='ai'?`linear-gradient(135deg,${C.surface},${C.teal}10)`:`linear-gradient(135deg,${C.teal}18,${C.mint}10)`,border:`1px solid ${m.role==='ai'?C.border:C.teal+'32'}`,fontSize:13,lineHeight:1.65,color:C.text}}>{m.text}</div></div>))}
      {slots&&(<div style={{animation:'su .3s ease',marginBottom:10}}><div style={{fontSize:11,color:C.muted,textAlign:'center',marginBottom:6}}>{lang==='fr'?'📅 Choisissez un créneau':'📅 Choose a slot'}</div><div style={{display:'flex',flexDirection:'column',gap:5}}>{slots.map(s=>(<button key={s.id} onClick={()=>setSel(s.id)} style={{padding:'11px 13px',background:sel===s.id?C.teal+'22':C.surface,border:`1.5px solid ${sel===s.id?C.teal:C.border}`,borderRadius:10,cursor:'pointer',textAlign:'left',transition:'all .2s'}}><div style={{fontSize:13,fontWeight:600,color:C.text,marginBottom:1}}>📅 {s.label}</div><div style={{fontSize:11,color:C.muted}}>{s.provider} · {s.dept}</div></button>))}</div>{sel&&<button onClick={confirmSlot} style={{width:'100%',marginTop:8,padding:'10px',background:C.teal,border:'none',borderRadius:10,color:C.midnight,fontSize:13,fontWeight:700,cursor:'pointer',animation:'su .2s ease'}}>{lang==='fr'?'✓ Confirmer ce rendez-vous':'✓ Confirm this appointment'}</button>}</div>)}
      {load&&(<div style={{display:'flex',alignItems:'center',gap:5,padding:'4px 8px',animation:'su .2s ease'}}><div style={{width:20,height:20,borderRadius:'50%',background:`linear-gradient(135deg,${C.teal},${C.mint})`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:8,marginRight:3}}>✦</div>{[0,1,2].map(i=>(<div key={i} style={{width:6,height:6,borderRadius:'50%',background:C.teal,animation:'db 1.1s ease-in-out infinite',animationDelay:`${i*.14}s`}}/>))}</div>)}
    </div>
    {msgs.length<=1&&!load&&(<div style={{padding:'0 10px 6px',flexShrink:0}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5}}>{ql.map((q:any)=>(<button key={q.l} onClick={()=>send(q.m)} style={{padding:'7px 9px',background:C.surface,border:`1px solid ${C.border}`,borderRadius:8,cursor:'pointer',textAlign:'left',fontSize:11,color:C.text,display:'flex',alignItems:'center',gap:5}}><span style={{fontSize:12}}>{q.i}</span>{q.l}</button>))}</div></div>)}
    <div style={{padding:'8px 10px 13px',background:C.surface,borderTop:`1px solid ${C.border}`,flexShrink:0}}>
      {vErr&&<div style={{fontSize:11,color:C.urgent,textAlign:'center',marginBottom:4}}>{vErr}</div>}
      {vocal?(<div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:8}}><button onClick={listen?stopL:startL} disabled={load} style={{width:58,height:58,borderRadius:'50%',background:listen?`linear-gradient(135deg,${C.mint},${C.teal})`:load?C.border:`linear-gradient(135deg,${C.teal},${C.mint})`,border:'none',cursor:load?'not-allowed':'pointer',fontSize:22,display:'flex',alignItems:'center',justifyContent:'center',boxShadow:listen?`0 0 24px ${C.mint}55`:`0 0 14px ${C.teal}28`,transition:'all .3s'}}>{listen?'⬛':load?'⋯':'🎤'}</button><div style={{fontSize:11,color:C.muted,textAlign:'center'}}>{listen?(lang==='fr'?'Parlez... (⬛ pour envoyer)':'Speak... (⬛ to send)'):load?(lang==='fr'?'Traitement...':'Processing...'):(lang==='fr'?'Appuyez pour parler':'Press to speak')}</div></div>):(<div style={{display:'flex',gap:6}}><input value={inp} onChange={e=>setInp(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&send(inp)} placeholder={lang==='fr'?'Écrivez votre message...':'Type your message...'} disabled={load} style={{flex:1,padding:'9px 12px',background:C.midnight,border:`1px solid ${C.border}`,borderRadius:10,color:C.text,fontSize:13,outline:'none',fontFamily:"'Inter',sans-serif"}}/><button onClick={listen?stopL:startL} disabled={load} style={{width:38,height:38,borderRadius:9,background:listen?C.mint+'28':C.midnight,border:`1px solid ${listen?C.mint:C.border}`,cursor:'pointer',fontSize:15,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>{listen?'⬛':'🎤'}</button><button onClick={()=>send(inp)} disabled={!inp.trim()||load} style={{width:38,height:38,borderRadius:9,background:inp.trim()&&!load?C.teal:C.border,border:'none',cursor:inp.trim()&&!load?'pointer':'not-allowed',fontSize:14,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,transition:'background .2s'}}>▸</button></div>)}
    </div>
  </div>);
}
