// VITARA — Scénarios conversationnels (compact, focus sur les cas spéciaux)
export interface Scenario { id:string; title:string; tags:string[]; dept?:string; priority:number; context:string; }

export const SCENARIOS: Scenario[] = [
  { id:'S001', title:'Nouveau patient', tags:['nouveau','new','premier','first','jamais venu','inscription'], dept:'all', priority:1,
    context:`Nouveau patient: collecter progressivement (UNE info à la fois): prénom → nom → DOB → tél → courriel → RAMQ → service désiré` },
  { id:'S002', title:'Patient existant', tags:['existant','existing','déjà venu','been before','suivi','follow-up','mon médecin'], dept:'all', priority:1,
    context:`Patient existant: demander nom + téléphone → vérifier dossier → proposer médecin habituel en priorité` },
  { id:'S003', title:'Annulation RDV', tags:['annuler','cancel','annulation','ne peux pas venir','cannot come'], dept:'all', priority:1,
    context:`Annulation: identifier RDV (nom+date) → confirmer annulation → proposer nouveau créneau → SMS confirmation` },
  { id:'S004', title:'Changement RDV', tags:['changer','change','modifier','reschedule','reporter','autre date'], dept:'all', priority:1,
    context:`Changement: identifier RDV actuel → nouvelle préférence horaire → 3 créneaux → nouveau code VIT-XXXX` },
  { id:'S005', title:'URGENCE VITALE', tags:['urgence','emergency','911','inconscient','chest pain','douleur poitrine','ambulance','overdose','ne respire plus'], dept:'urgence', priority:1,
    context:`URGENCE ABSOLUE: intent "emergency" + dire "Composez le 911 immédiatement" + rester calme. Ne pas garder en ligne. 811 pour Info-Santé.` },
  { id:'S006', title:'Urgence non-vitale', tags:['urgent','aujourd\'hui','douleur aiguë','fièvre élevée','infection grave'], dept:'all', priority:1,
    context:`Urgence modérée: évaluer douleur 0-10 → si >8: urgence/911 → si <7: créneau aujourd'hui ou lendemain → téléconsultation disponible` },
  { id:'S007', title:'Physiothérapie — CNESST', tags:['CNESST','accident travail','work accident','physio cnesst'], dept:'physiotherapie', priority:1,
    context:`CNESST physio: demander numéro dossier CNESST + nom employeur + date accident → Shaheer Haider ou Omar Khalil (CNESST certifiés)` },
  { id:'S008', title:'Physiothérapie — SAAQ', tags:['SAAQ','accident auto','car accident','physio saaq','accident route'], dept:'physiotherapie', priority:1,
    context:`SAAQ physio: demander numéro réclamation SAAQ + date accident + rapport police si dispo → Shaheer Haider ou Sophie Tremblay (SAAQ certifiés)` },
  { id:'S009', title:'Physiothérapie — Post-op', tags:['post-op','chirurgie','opération','surgery','prothèse','LCA','ménisque','épaule chirurgie'], dept:'physiotherapie', priority:1,
    context:`Post-op: demander type chirurgie + date + chirurgien + protocole → éval initiale 60min obligatoire → Omar Khalil spécialisé post-chirurgical` },
  { id:'S010', title:'Médecin de famille — choix', tags:['médecin de famille','family doctor','mon médecin','choisir médecin','liste médecins'], dept:'medecine-familiale', priority:1,
    context:`Choix médecin: présenter liste GMF (Dr. Awada, Caricevic, Fruchtermann, Kalim, Moriconi, Moynihan, Ohayon-Gabbay, Serfaty, Préfontaine). Patient peut dire nom, l'épeler, ou dire "je ne sais pas" → proposer médecin disponible.` },
  { id:'S011', title:'Pédiatrie urgente', tags:['enfant','bébé','nourrisson','baby','fièvre enfant','bébé malade'], dept:'pediatrie', priority:1,
    context:`Pédiatrie: DEMANDER L'ÂGE EN PREMIER. Bébé <3 mois + fièvre >38°C = URGENCE PÉDIATRIQUE IMMÉDIATE (CHU Sainte-Justine / Montreal Children's). Enfant >3 mois + fièvre >39°C depuis 48h = RDV urgent.` },
  { id:'S012', title:'Psychologie — crise', tags:['psy','anxiété','dépression','stress','burn-out','mental','suicidaire','crise','help'], dept:'psychologie', priority:1,
    context:`Santé mentale: aborder avec douceur. Si pensées suicidaires → donner 1-866-APPELLE (24/7) immédiatement. Téléconsultation très populaire. Dr. Hassan parle arabe.` },
  { id:'S013', title:'Renouvellement ordonnance', tags:['renouvellement','renewal','ordonnance','prescription','médicament'], dept:'medecine-familiale', priority:1,
    context:`Renouvellement: demander nom médicament + posologie + pharmacie préférée → délai 24-48h → consultation courte 15min si >6 mois sans visite` },
  { id:'S014', title:'Prise de sang / Analyses', tags:['prise de sang','blood test','analyse','prélèvement','laboratoire','urine','bilan sanguin'], dept:'prelevements', priority:1,
    context:`Prélèvements: vérifier ordonnance médicale (requise) → instructions spéciales (jeun?) → RDV 15min → RAMQ couvert avec prescription` },
  { id:'S015', title:'English — Full flow', tags:['hello','hi','good morning','english','i need','book','appointment','i want'], dept:'all', priority:1,
    context:`English patient: follow 10-step workflow in English. GMF doctors speak English. Dr. Hassan speaks Arabic + English + French. Physiotherapists Shaheer Haider and Omar Khalil speak English.` },
  { id:'S016', title:'Arabe — Flux complet', tags:['مرحبا','أريد','موعد','طبيب','ألم','مساعدة'], dept:'all', priority:1,
    context:`مريض عربي: اتباع سير العمل العشري بالعربية. Dr. Awada يتحدث العربية. Dr. Serfaty يتحدث العربية. Dr. Hassan يتحدث العربية.` },
  { id:'S017', title:'Assurance — RAMQ', tags:['RAMQ','carte soleil','numéro assurance maladie','ramq number'], dept:'all', priority:2,
    context:`RAMQ: format 4 lettres + 8 chiffres (ex: MART85061298). Date expiration sur carte. Si pas de RAMQ: service peut être payant.` },
  { id:'S018', title:'Téléconsultation', tags:['téléconsultation','video','virtuel','online','à distance','zoom','teams'], dept:'all', priority:2,
    context:`Téléconsultation: disponible médecine familiale, psychologie, nutrition, suivi physio. Lien Cortexa envoyé SMS 30min avant. Besoin: internet stable + caméra.` },
  { id:'S019', title:'Nutrition — Diabète', tags:['diabète','diabetes','glycémie','insuline','sucre','nutrition diabète'], dept:'nutrition', priority:2,
    context:`Nutrition diabète: Youssef Benali spécialisé diabète. Demander: type 1 ou 2? Médication actuelle? Objectif glycémique? Assurance couvre si prescription médicale.` },
  { id:'S020', title:'Vaccination adulte', tags:['vaccination adulte','vaccin grippe','flu shot','covid vaccin','hépatite'], dept:'medecine-familiale', priority:2,
    context:`Vaccination adulte: Grippe oct-nov (sans RDV, 15min). COVID, hépatite, zona: RDV 20min. Apporter carnet vaccination. Gratuit RAMQ pour grippe.` },
  { id:'S021', title:'Bilan annuel', tags:['bilan annuel','checkup','examen médical','physique annuel','prévention'], dept:'medecine-familiale', priority:2,
    context:`Bilan annuel: RDV 40min. Prise de sang AVANT (requête envoyée par courriel, à jeun). Dépistages selon âge: mammographie 50+, coloscopie 50+, Pap test.` },
  { id:'S022', title:'Assurance privée', tags:['assurance privée','blue cross','desjardins','sunlife','manulife','assurance complémentaire'], dept:'all', priority:2,
    context:`Assurance privée: facturation directe disponible (formulaire 1ère visite). Acceptées: Croix Bleue, Desjardins, SSQ, GMS, Sun Life, Manulife. Physio/psy/nutrition partiellement couverts.` },
  { id:'S023', title:'Paiement — tarifs', tags:['prix','coût','tarif','combien','how much','gratuit','payant'], dept:'all', priority:2,
    context:`Tarifs (sans assurance): Physio 80-120$/séance | Psy 130-180$/séance | Nutrition 90-130$/séance | Ergo 100-150$/séance. Médecine familiale couverte RAMQ. Paiement: carte, débit, comptant.` },
  { id:'S024', title:'Infos clinique', tags:['horaires','adresse','où','parking','stationnement','transport','ouvert'], dept:'all', priority:3,
    context:`Clinique: 1234 Boul. Laval, Laval QC | Tél: (514)555-0100 | Lun-Ven 7h30-20h, Sam 8h-17h, Dim fermé. Stationnement gratuit 2h (valider réception). Bus 70 arrêt devant.` },
  { id:'S025', title:'Portail patient', tags:['portail','portal','compte','app','application','login','mot de passe','vitara-patient'], dept:'all', priority:3,
    context:`Portail: vitara-patient.ca (web + iOS/Android). RDV 24/7, résultats, messagerie. Inscription: carte RAMQ + date naissance + courriel. Support: 1-855-VITARA-2.` },
];
